### ISSUE TITLE
Secrets still in commit history

### ISSUE THREAD

**Issue by kierenj** [tamhinsf/ChannelSurf#2]
You'll need to rewrite history to get rid of this..

**Comment by tamhinsf** [comment]
Hey - thanks for the heads up. The two items aren't really secrets, but I'll get around to removing them at some point.

**Comment by tamhinsf** [comment]
History re-written, but we have a Catch-22 here due to the issue described at the link below and the fact that we were linking to it.  While I've removed the link in your original comment, a copy could still be floating around out there.  

https://github.com/isaacs/github/issues/1081

All said, I'm going to close this.  Not really secrets exposed, bug again thanks for the heads up.
